### ISSUE TITLE
Random failures of t/04-opml.t

### ISSUE THREAD

**Issue by eserte** [dotandimet/Mojolicious-Plugin-FeedReader#1]
http://matrix.cpantesters.org/?dist=Mojolicious-Plugin-FeedReader%200.07 shows a few fail reports. In fact, if I run t/04-opml.t in a loop, then it always fails after 100-200 iterations. It seems that the problem is that the 'Kiwis By Beat' feed in sputnik-feeds.opml.xml does not have a htmlUrl defined, so the test fails if it happens that feed number 0 or 293 is this one.

**Comment by dotandimet** [comment]
Thanks for this! Sorry I wasn't responsive - I missed these issues because I wasn't getting mail from github (also there might have been some noise in the cpantesters errors that made me miss this too).
I just pushed a fix (removed the order-dependant tests), not sure if it's worth another release on its own.
